// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEhu3Jm4ErTpYJCFXJZPdjMiHs1UMvl3U',
    appId: '1:1064915480001:web:6c8b020d4d39a799629340',
    messagingSenderId: '1064915480001',
    projectId: 'wirakarsa-ccfdf',
    authDomain: 'wirakarsa-ccfdf.firebaseapp.com',
    databaseURL: 'https://wirakarsa-ccfdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wirakarsa-ccfdf.firebasestorage.app',
    measurementId: 'G-QX7H6442DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI2EO4DZ0rpXMKQCYqF8Tr-7PpdHkRXQc',
    appId: '1:1064915480001:android:249d479a2f7d7cc3629340',
    messagingSenderId: '1064915480001',
    projectId: 'wirakarsa-ccfdf',
    databaseURL: 'https://wirakarsa-ccfdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wirakarsa-ccfdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSZVsnjgYGCTjn6-2DGicyeKAzUO3BaA',
    appId: '1:1064915480001:ios:a3d3893a42eb38ab629340',
    messagingSenderId: '1064915480001',
    projectId: 'wirakarsa-ccfdf',
    databaseURL: 'https://wirakarsa-ccfdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wirakarsa-ccfdf.firebasestorage.app',
    iosBundleId: 'com.wirapath.wirapath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEhu3Jm4ErTpYJCFXJZPdjMiHs1UMvl3U',
    appId: '1:1064915480001:web:68be22f9b647cdbf629340',
    messagingSenderId: '1064915480001',
    projectId: 'wirakarsa-ccfdf',
    authDomain: 'wirakarsa-ccfdf.firebaseapp.com',
    databaseURL: 'https://wirakarsa-ccfdf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wirakarsa-ccfdf.firebasestorage.app',
    measurementId: 'G-H24LTGCWZ1',
  );
}
